// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Category struct {
	ID   int64
	Name string
}

type Transaction struct {
	ID           int64
	Name         string
	Cost         float64
	Date         time.Time
	CategoriesID sql.NullInt64
}
